### PR TITLE
Experimental Camera Component

### PR DESCRIPTION
**Pull request by jtmcdole**
Shows the camera component.  From here, you could create more cameras and show either the same world as a mini-map, or a stylized map in another "world".

### CODE REVIEW

**Comment by jtmcdole** [comment]
Not meant for merging to main.

**Comment by ufrshubham** [comment]
Looks pretty bad in game 
image

**Comment by ufrshubham** [comment]
@jtmcdole if this is still a work in progress, you can convert this PR into a draft.

**Comment by jtmcdole** [comment]
Totally a work in progress - from the youtube conversation: was meant solely as a experimental branch showing the new camera system.

**Comment by ufrshubham** [comment]
I've migrated the project to new camera system. Closing this PR now.

**Pull request closed without merging**
